name = "text-sushidesu-com"
main = "./src/index.tsx"
compatibility_date = "2025-08-03"
routes = [{ pattern = "text.sushidesu.com", custom_domain = true }]

[[d1_databases]]
binding = "DB"
database_name = "note-sushidesu-com"
database_id = "878221ad-1628-4e71-822d-43a2695ee3c4"
migrations_dir = "./migration"
